stages:
  - build
  - test

build-code-job:
  stage: build
  script:
    - echo "Going to try and build the API:"
    - cd ./Backend
    - mvn clean install

test-code-job1:
  stage: test
  script:
    - echo "Check if the file was built?"
    - ls /home/gitlab-runner/.m2/repository/coms309/PaloAPI/1.0.0/PaloAPI-1.0.0.jar
    - echo "This is broken rn?"
