stages:
  - build
  - test
  - deploy
  - androidbuild
  - androidtest

build-code-job:
  only:
    refs:
      - master
    changes:
      - Backend/**/*
  stage: build
  tags:
    - backend
  only:
    refs:
      - master
    changes:
      - Backend/**/*
  script:
    - mkdir -p /home/gitlab-runner/testBuild
    - echo "Going to try and build the API:"
    - cd ./Backend
    - mvn clean install -DskipTests
    - cp -r ./target/* /home/gitlab-runner/testBuild/

test-code-job1:
  only:
    refs:
      - master
    changes:
      - Backend/**/*
  stage: test
  tags:
    - backend
  only:
    refs:
      - master
    changes:
      - Backend/**/*
  script:
    - echo "Running JUnit Mockito test :-)"
    - cd ./Backend
    - mvn test

test-code-deploy:
  stage: deploy
  tags:
    - backend
  only:
    refs:
      - master
    changes:
      - Backend/**/*
  script:
    - echo "This will deploy the tested build"
    - cp -r /home/gitlab-runner/testBuild/* /palo/
    - sudo systemctl restart palo

android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME='pwd'/.gradle
    - chmod +x ./Frontend/Palo/gradlew
  tags:
    - frontend
  script:
    - cd Frontend/Palo
    - ./gradlew build
  artifacts:
    paths:
      - Android_test/app/build/outputs/

android-test:
  image: javiersantos/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER='pwd'/.gradle
    - chmod +x ./Frontend/Palo/gradlew
  tags:
    - frontend
  script:
    - cd Frontend/Palo
    - ./gradlew test