stages:
  - build
  - test

build-code-job:
  stage: build
  script:
    - echo "Going to try and build the API:"
    - cd ./Backend
    - mvn clean install

test-code-job1:
  stage: test
  script:
    - echo "Check if the file was built?"
    - ls ./
    - echo "This is broken rn"
